package:
  name: perl-sort-key
  version: "1.33"

source:
  fn: Sort-Key-1.33.tar.gz
  url: http://cpan.metacpan.org/authors/id/S/SA/SALVA/Sort-Key-1.33.tar.gz
  md5: a37ab0da0cfdc26e57b4c79e39f6d98f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - perl-threaded
    - perl-extutils-makemaker

  run:
    - perl-threaded

test:
  # Perl 'use' tests
  imports:
    - Sort::Key
    - Sort::Key::Maker
    - Sort::Key::Multi
    - Sort::Key::Natural
    - Sort::Key::Register
    - Sort::Key::Types

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://metacpan.org/pod/Sort-Key
  license: unknown
  summary: 'the fastest way to sort anything in Perl'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
