package:
  name: lcaclassifier
  version: 3.0.7

source:
  url: https://github.com/lanzen/CREST/releases/download/3.0.7/LCAClassifierV3.0.7.tar.gz
  sha256: 764c3e6cd7e7c0e0ee8c924fdf66a77f42033be840d38b9dba8c5f3b8ef5b988

build:
  skip: True  # [py3k]
  number: 0
  entry_points:
    - classify = LCAClassifier.classify:main
    - nds2CREST = LCAClassifier.nds2CREST:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - biom-format
    - biopython

test:
  commands:
    - classify -h
    - nds2CREST -h

about:
  home: https://github.com/lanzen/CREST/
  license: GPL 3.0
  summary: LCAClassifier is a program for taxonomic classification of environmental sequence datasets.
